source "https://rubygems.org"

gem "fastlane"
gem "abbrev"  # Add this line to resolve the LoadError

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)